set(ARDUINO_CORE_DIR $ENV{HOME}/gitrepo/ArduinoCore-mbed)
set(ARDUINO_API_DIR $ENV{HOME}/gitrepo/ArduinoCore-api)

file(GLOB ARDUINO_CORE_SRCS ${ARDUINO_CORE_DIR}/cores/arduino/*.cpp ${ARDUINO_CORE_DIR}/cores/arduino/**/*.cpp)
file(GLOB ARDUINO_TARGET_SRCS ${ARDUINO_CORE_DIR}/variants/NICLA_VISION/*.cpp)
file(GLOB ARDUINO_API_SRCS ${ARDUINO_API_DIR}/api/*.cpp ${ARDUINO_API_DIR}/api/**/*.cpp)
file(GLOB ARDUINO_API_C_SRCS ${ARDUINO_API_DIR}/api/*.c ${ARDUINO_API_DIR}/api/**/*.c)
file(GLOB ARDUINO_CORE_C_SRCS ${ARDUINO_CORE_DIR}/cores/arduino/*.c ${ARDUINO_CORE_DIR}/cores/arduino/**/*.c)

set(LINKER_SCRIPT ${ARDUINO_CORE_DIR}/variants/NICLA_VISION/linker_script.ld)

set(ARDUINO_INCLUDE_DIRS
    ${ARDUINO_API_DIR}
    ${ARDUINO_API_DIR}/api/deprecated
    ${ARDUINO_API_DIR}/api/deprecated-avr-comp
    ${ARDUINO_CORE_DIR}/cores/arduino
    ${ARDUINO_CORE_DIR}/cores/arduino/USB
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2/Include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2/RTX
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include1
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/device
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/device/RTE
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/device/RTE/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/device/rtos
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/cmsis/device/rtos/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/common
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/compatibility
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/compatibility/ble
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/gap
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/gatt
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/include/ble/services
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/sec
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/sec/common
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/cfg
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/dm
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/hci
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/l2c
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/smp
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/platform/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/wsf
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/wsf/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/libraries/cordio_stack/wsf/include/util
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source/common
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source/cordio
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source/cordio/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source/cordio/stack_adaptation
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source/generic
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/FEATURE_BLE/source/pal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include/cellular
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include/cellular/framework
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include/cellular/framework/API
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include/cellular/framework/AT
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include/cellular/framework/common
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/cellular/include/cellular/framework/device
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/atmel-rf-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/atmel-rf-driver/atmel-rf-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/atmel-rf-driver/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/mcr20a-rf-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/Altair
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/Altair/ALT1250
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/Altair/ALT1250/PPP
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/GEMALTO
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/GEMALTO/CINTERION
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/GENERIC
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/GENERIC/GENERIC_AT3GPP
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/MultiTech
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/MultiTech/DragonflyNano
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/MultiTech/DragonflyNano/PPP
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/QUECTEL
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/QUECTEL/BC95
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/QUECTEL/BG96
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/QUECTEL/EC2X
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/QUECTEL/M26
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/QUECTEL/UG96
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/RiotMicro
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/RiotMicro/AT
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/TELIT
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/TELIT/HE910
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/TELIT/ME310
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/TELIT/ME910
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/UBLOX
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/UBLOX/AT
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/UBLOX/N2XX
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/cellular/UBLOX/PPP
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/COMPONENT_WHD
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/COMPONENT_WHD/interface
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/COMPONENT_WHD/network
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/COMPONENT_WHD/utils
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/TARGET_STM
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/TARGET_STM/TARGET_STM32H7
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/emac/TARGET_STM/TARGET_STM32H7/lan8742
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/mbedtls/TARGET_STM
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc/PN512
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc/PN512/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc/PN512/include/nfc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc/PN512/include/nfc/controllers
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc/PN512/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/nfc/PN512/source/transceiver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/whd-bsp-integration
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver/inc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver/resources
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver/resources/resource_imp
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver/src
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver/src/bus_protocols
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/COMPONENT_WHD/wifi-host-driver/src/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/esp8266-driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/drivers/wifi/esp8266-driver/ESP8266
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/mbed-coap
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/mbed-coap/mbed-coap
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/mbed-coap/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/mbed-coap/source/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/nanostack-libservice
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/nanostack-libservice/mbed-client-libservice
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/nanostack-libservice/mbed-client-libservice/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/ppp
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/ppp/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/ppp/include/polarssl
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/libraries/ppp/include/ppp
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan/include/lorawan
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan/lorastack
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan/lorastack/mac
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan/lorastack/phy
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lorawan/system
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/include/lwipstack
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip-sys
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip-sys/arch
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/compat
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/compat/posix
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/compat/posix/arpa
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/compat/posix/net
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/compat/posix/sys
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/lwip
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/lwip/priv
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/lwip/prot
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/lwipstack/lwip/src/include/netif
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/mbedtls
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/mbedtls/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/mbedtls/include/mbedtls
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/mbedtls/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/mbedtls/platform/inc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/mbedtls/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/netsocket
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/netsocket/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/netsocket/include/netsocket
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/include/nfc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/include/nfc/ndef
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/include/nfc/ndef/common
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/acore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/acore/acore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/ndef
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/tech
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/tech/iso7816
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/tech/isodep
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/tech/type4
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/connectivity/nfc/libraries/stack/transceiver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/device_key
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/device_key/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/device_key/include/device_key
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/include/drivers
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/include/drivers/interfaces
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/usb
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/usb/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/usb/include/usb
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/drivers/usb/include/usb/internal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/events
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/events/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/events/include/events
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/events/include/events/internal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/greentea-client
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/greentea-client/greentea-client
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/mbed-client-cli
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/mbed-client-cli/mbed-client-cli
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/unity
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/unity/unity
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/utest
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/features/frameworks/utest/utest
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/hal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/hal/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/hal/include/hal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/hal/usb
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/hal/usb/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/hal/usb/include/usb
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/cxxsupport
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/include/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/include/platform/internal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/mbed-trace
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/mbed-trace/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/mbed-trace/include/mbed-trace
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/randlib
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/randlib/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/randlib/include/mbed-client-randlib
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/randlib/include/mbed-client-randlib/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/platform/source/minimal-printf
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/rtos
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/rtos/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/rtos/include/rtos
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/rtos/include/rtos/internal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/rtos/source
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/COMPONENT_FLASHIAP
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/COMPONENT_FLASHIAP/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/COMPONENT_FLASHIAP/include/FlashIAP
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/COMPONENT_QSPIF
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/COMPONENT_QSPIF/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/COMPONENT_QSPIF/include/QSPIF
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/include/blockdevice
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/blockdevice/include/blockdevice/internal
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/fat
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/fat/ChaN
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/fat/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/fat/include/fat
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/include/filesystem
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefs
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefs/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefs/include/littlefs
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefs/littlefs
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefsv2
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefsv2/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefsv2/include/littlefsv2
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/filesystem/littlefsv2/littlefs
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/direct_access_devicekey
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/direct_access_devicekey/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/direct_access_devicekey/include/direct_access_devicekey
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/filesystemstore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/filesystemstore/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/filesystemstore/include/filesystemstore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/include/kvstore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/kv_config
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/kv_config/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/kv_config/include/kv_config
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/kvstore_global_api
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/kvstore_global_api/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/kvstore_global_api/include/kvstore_global_api
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/securestore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/securestore/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/securestore/include/securestore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/tdbstore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/tdbstore/include
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/storage/kvstore/tdbstore/include/tdbstore
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/CMSIS
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/STM32H7xx_HAL_Driver
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/STM32H7xx_HAL_Driver/Legacy
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/inc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/libCommon
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/libCommon/infra
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/libCommon/nxlog
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/libCommon/smCom
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/libCommon/smCom/T1oI2C
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/platform
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/platform/inc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/hostlib/hostLib/se05x_03_xx_xx
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/ex
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/ex/inc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/ex/src
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/inc
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/plugin
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/plugin/mbedtls
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/port
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/COMPONENT_SE050/sss/port/default
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION/COMPONENT_WHD
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION/COMPONENT_WHD/interface
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION/COMPONENT_WHD/port
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION/COMPONENT_WHD/resources
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION/COMPONENT_WHD/resources/firmware/COMPONENT_4343W_FS
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_NICLA_VISION/COMPONENT_WHD/resources/nvram
    ${ARDUINO_CORE_DIR}/cores/arduino/mbed/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_STM32H747xI_CM7
    ${ARDUINO_CORE_DIR}/variants/NICLA_VISION
)

set(ARDUINO_COMPILE_DEFINITIONS
    ARM_MATH_CM7
    CM4_BOOT_BY_APPLICATION
    __CMSIS_RTOS
    COMPONENT_4343W_FS=1
    COMPONENT_CYW43XXX=1
    COMPONENT_FLASHIAP=1
    COMPONENT_QSPIF=1
    COMPONENT_SE050=1
    COMPONENT_WHD=1
    CORE_CM7
    __CORTEX_M7
    CYW43XXX_UNBUFFERED_UART
    DEVICE_ANALOGIN=1
    DEVICE_ANALOGOUT=1
    DEVICE_CAN=1
    DEVICE_CRC=1
    DEVICE_FLASH=1
    DEVICE_I2C=1
    DEVICE_I2C_ASYNCH=1
    DEVICE_I2CSLAVE=1
    DEVICE_INTERRUPTIN=1
    DEVICE_LPTICKER=1
    DEVICE_MPU=1
    DEVICE_PORTIN=1
    DEVICE_PORTINOUT=1
    DEVICE_PORTOUT=1
    DEVICE_PWMOUT=1
    DEVICE_QSPI=1
    DEVICE_RESET_REASON=1
    DEVICE_RTC=1
    DEVICE_SERIAL=1
    DEVICE_SERIAL_FC=1
    DEVICE_SLEEP=1
    DEVICE_SPI=1
    DEVICE_SPI_ASYNCH=1
    DEVICE_SPISLAVE=1
    DEVICE_STDIO_MESSAGES=1
    DEVICE_TRNG=1
    DEVICE_USBDEVICE=1
    DEVICE_USTICKER=1
    DEVICE_WATCHDOG=1
    EXTRA_IDLE_STACK_REQUIRED
    FEATURE_BLE=1
    FLOW_SILENT
    __FPU_PRESENT=1
    __MBED__=1
    MBED_BUILD_TIMESTAMP=1662124959.407307
    __MBED_CMSIS_RTOS_CM
    MBED_TICKLESS
    MBEDTLS_FS_IO
    MBEDTLS_SHA1_C
    METAL_INTERNAL
    METAL_MAX_DEVICE_REGIONS=2
    NO_ATOMIC_64_SUPPORT
    QSPI_NO_SAMPLE_SHIFT
    RPMSG_BUFFER_SIZE=100
    STM32H747xx
    T1oI2C
    T1oI2C_UM11225
    TARGET_CORDIO
    TARGET_CORTEX
    TARGET_CORTEX_M
    TARGET_LIKE_CORTEX_M7
    TARGET_LIKE_MBED
    TARGET_M7
    TARGET_MCU_STM32
    TARGET_MCU_STM32H7
    TARGET_MCU_STM32H747xI
    TARGET_MCU_STM32H747xI_CM7
    TARGET_NAME=NICLA_VISION
    TARGET_NICLA_VISION
    TARGET_RELEASE
    TARGET_RTOS_M4_M7
    TARGET_STM
    TARGET_STM32H7
    TARGET_STM32H747xI
    TARGET_STM32H747xI_CM7
    TOOLCHAIN_GCC
    TOOLCHAIN_GCC_ARM
    TRANSACTION_QUEUE_SIZE_SPI=2
    USE_FULL_LL_DRIVER
    USE_HAL_DRIVER
    VIRTIO_MASTER_ONLY
    MBED_NO_GLOBAL_USING_DIRECTIVE=1
    CORE_MAJOR=3
    CORE_MINOR=3
    CORE_PATCH=0
    USE_ARDUINO_PINOUT
    ARDUINO_NICLA_VISION
    ARDUINO_ARCH_MBED
    ARDUINO
)

set(ARDUINO_COMPILE_OPTIONS
    -fdata-sections
    -ffunction-sections
    -fmessage-length=0
    -fno-exceptions
    -fomit-frame-pointer
    -funsigned-char
    -c
    -Os
    -Wall
    -Wextra
    -Wno-missing-field-initializers
    -Wno-unused-parameter
    -mcpu=cortex-m7
    -mfloat-abi=softfp
    -mfpu=fpv5-d16
    -mthumb
    -MMD
    -g3
    -nostdlib

    -DAPPLICATION_ADDR=0x8040000
    -DAPPLICATION_RAM_ADDR=0x24000000
    -DAPPLICATION_RAM_SIZE=0x80000
    -DAPPLICATION_SIZE=0x1c0000
    -DMBED_RAM1_SIZE=0x80000
    -DMBED_RAM1_START=0x24000000
    -DMBED_RAM_SIZE=0x80000
    -DMBED_RAM_START=0x24000000
    -DMBED_ROM_SIZE=0x200000
    -DMBED_ROM_START=0x8000000
    -DMBED_TRAP_ERRORS_ENABLED=1
)

set(ARDUINO_COMMON_LINKFLAGS
    -Wl,--gc-sections
    -w -Wl,--as-needed
    -DMBED_APP_SIZE=0x1c0000
    -DMBED_APP_START=0x8040000
    -DMBED_BOOT_STACK_SIZE=1024
    -DMBED_RAM1_SIZE=0x80000
    -DMBED_RAM1_START=0x24000000
    -DMBED_RAM_SIZE=0x80000
    -DMBED_RAM_START=0x24000000
    -DMBED_ROM_SIZE=0x200000
    -DMBED_ROM_START=0x8000000
    -DXIP_ENABLE=0
    -Wl,--gc-sections
    -Wl,--wrap,_calloc_r
    -Wl,--wrap,_free_r
    -Wl,--wrap,_malloc_r
    -Wl,--wrap,_memalign_r
    -Wl,--wrap,_realloc_r
    -Wl,--wrap,atexit
    -Wl,--wrap,exit
    -Wl,--wrap,main
    -Wl,-n
    -mcpu=cortex-m7
    -mfloat-abi=softfp
    -mfpu=fpv5-d16
    -mthumb
)

set(ARDUINO_CLOSING_LINKFLAGS
    -Wl,--no-whole-archive
    -Wl,--start-group
    -lstdc++
    -lsupc++
    -lm
    -lc
    -lgcc
    -lnosys
    -Wl,--end-group
)